# Generated by Django 6.0.7 on 2026-07-23 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='video',
        ),
        migrations.RemoveField(
            model_name='watchhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='watchhistory',
            name='video',
        ),
        migrations.CreateModel(
            name='MoneroPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_xmr', models.DecimalField(decimal_places=8, max_digits=18)),
                ('payment_type', models.CharField(choices=[('AD', 'Advertisement Boost'), ('SUB', 'Platform Subscription / Tip')], max_length=3)),
                ('tx_hash', models.CharField(max_length=255, unique=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='WatchHistory',
        ),
    ]
